ddcz/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.generic.base import RedirectView, TemplateView
from django.views.decorators.cache import cache_page

from .feeds import PhorumFeed, CompleteNewsFeed
from . import views
from .views import news, tavern, misc, email
from .views.legacy import legacy_router, print_legacy_router

app_name = "ddcz"

urlpatterns = [
    path("", RedirectView.as_view(url="aktuality/", permanent=False)),
    ### Legacy redirects from stare.dracidoupe.cz
    path("index.php", legacy_router, name="legacy-router"),
    re_path(
        "code/(?P<page_category>[a-zA-Z0-9_-]+)/(?P<page_category_second>[a-zA-Z0-9_-]+)_tisk.php",
        print_legacy_router,
        name="legacy-router-print",
    ),
    re_path(
        r"^ikonky/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.USER_ICON_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-icons",
    ),
    re_path(
        r"^fotogalerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-photogallery",
    ),
    re_path(
        r"^galerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-gallery",
    ),
    # It's gone, Dave
    re_path(r"^(moudrasova|img|static|skiny|chat)/", RedirectView.as_view()),
    ### Common pages for bots etc.
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("staticfiles/robots.txt", RedirectView.as_view(url="/robots.txt")),
    path(
        "ads.txt",
        TemplateView.as_view(template_name="ads.txt", content_type="text/plain"),
    ),
    path(
        ".well-known/security.txt",
        TemplateView.as_view(template_name="security.txt", content_type="text/plain"),
    ),
    # Prefetch for Google Chrome
    # Courtesy of https://webmasters.stackexchange.com/a/139570
    path(
        ".well-known/traffic-advice",
        TemplateView.as_view(
            template_name="traffic-advice.json",
            content_type="application/trafficadvice+json",
        ),
    ),
    ### Creations and Creative Pages
    path(
        "rubriky/<creative_page_slug>/", views.creative_page_list, name="creation-list"
    ),
    path(
        "rubriky/<creative_page_slug>/koncepce/",
        views.creative_page_concept,
        name="creative-page-concept",
    ),
    path(
        "rubriky/<creative_page_slug>/kontrola-html/",
        views.creative_page_html_check,
        name="creative_page_html_check",
    ),
    # path(
    #     "rubriky/<creative_page_slug>/<int:creation_id>-<creation_slug>/",
    #     views.creation_detail,
    #     name="creation-detail",
    # ),
    re_path(
        "^rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/$",
        views.creation_detail,
        name="creation-detail",
    ),
    re_path(
        "rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/obr_pris/(?P<image_path>.+)",  # /(?P<image_path_name>\w+)",
        views.creation_detail_image,
        name="creation-detail-image",
    ),
    re_path(
        r"obr_pris/(?P<image_path>[\w\/]+\.[\w]+)",
        views.creation_detail_image_legacy,
        name="creation-legacy-detail-image",
    ),
    # Standard list and detail are under creation pages above,
    # Those are for executing redirect to download/quest location
    path("download/<int:download_id>/", views.download_file, name="download-file"),
    path(
        "dobrodruzstvi/<int:quest_id>/",
        views.quest_view_redirect,
        name="quest-view-legacy-redirect",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)-(?P<quest_slug>[a-zA-Z0-9_-]+)/$",
        views.quest_view_redirect,
        name="quest-view",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)(-)?(?P<quest_slug>[a-zA-Z0-9_-]+)?/(?P<leftover>.*)$",
        views.quest_view_redirect_rest,
        name="quest-view-rest",
    ),
    ### User handling
    path("uzivatele/", views.users_list, name="users-list"),
    path("uzivatel/prihlaseni/", views.login, name="login-action"),
    path("registrace/", views.sign_up, name="sign-up"),
    path("uzivatel/odhlaseni/", views.logout, name="logout-action"),
    path(
        "uzivatel/reset-hesla/",
        views.PasswordResetView.as_view(),
        name="password-reset",
    ),
    path(
        "uzivatel/reset-hesla/hotovo/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "uzivatel/zmena-hesla/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password-change",
    ),
    path(
        "uzivatel/zmena-hesla/hotovo/",
        views.PasswordResetCompleteView.as_view(),
        name="password-change-done",
    ),
    path(
        "uzivatel/<int:user_profile_id>-<nick_slug>/",
        views.user_profile,
        name="user-detail",
    ),
    path("autor/<int:author_id>-<slug>/", views.author_detail, name="author-detail"),
    ### User settings
    path("nastaveni/zmena-skinu/", views.change_skin, name="change-skin"),
    path("nastaveni/", views.user_settings, name="user-settings"),
    ### Emails
    path(
        "e-mail/antispam/potvrzeni/",
        TemplateView.as_view(template_name="emails/unsub-confirm.html"),
        name="email-antispam-confirm",
    ),
    path(
        "e-mail/antispam/<email_base64>-<unsub_token>/",
        email.antispam,
        name="email-antispam",
    ),
    ### Info sites
    path("aktuality/", news.list, name="news"),
    path("novinky/", news.newsfeed, name="newsfeed"),
    path("seznamka/", views.dating, name="dating"),
    path("seznamka/pridat/", views.misc.dating_create, name="dating-create"),
    path("inzerce/", views.market, name="market"),
    path("inzerce/pridej/", views.market_create, name="market-create"),
    path("inzerce/smaz/<int:id>/", views.market_delete, name="market-delete"),
    path("linky/", views.links, name="links-list"),
    ### Discussions & Tavern
    path("forum/", views.phorum, name="phorum-list"),
    ### RSS cheat: pretend we have unique links for items. We may in the future.
    path(
        "forum/<int:comment_id>/",
        RedirectView.as_view(url="/forum/", permanent=False),
        name="phorum-item",
    ),
    path("putyka/", tavern.list_tables, name="tavern-list"),
    path(
        "putyka/stul/<int:tavern_table_id>/prispevky/",
        tavern.table_posts,
        name="tavern-posts",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/nastenka/",
        tavern.notice_board,
        name="tavern-notice-board",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/administrace/",
        tavern.table_administration,
        name="tavern-table-admin",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/oblibit/",
        tavern.table_bookmark,
        name="tavern-bookmark",
    ),
    ### RSS & Feeds
    path(
        "rss/forum/",
        cache_page(settings.RSS_CACHE_INTERVAL)(PhorumFeed()),
        name="feed-phorum",
    ),
    path("rss/forum.xml", RedirectView.as_view(url="/rss/forum/", permanent=True)),
    path(
        "rss/novinky/",
        cache_page(settings.RSS_CACHE_INTERVAL)(CompleteNewsFeed()),
        name="feed-complete",
    ),
    path("rss/novinky.xml", RedirectView.as_view(url="/rss/novinky/", permanent=True)),
    ### Static Editorial Pages
    ### Would be easier to give them /static prefix, but it makes for ugly URL
    path(
        "co-je-draci-doupe/",
        views.editor_article,
        name="about-drd",
        kwargs={"slug": "co-je-draci-doupe"},
    ),
    path(
        "draci-manual/",
        views.editor_article,
        name="website-manual",
        kwargs={"slug": "draci-manual"},
    ),
    path(
        "otazky-a-odpovedi/",
        views.editor_article,
        name="faq",
        kwargs={"slug": "otazky-a-odpovedi"},
    ),
    path(
        "tvurci-a-redakce/",
        misc.web_authors_and_editors,
        name="web-authors-and-editors",
    ),
    path("posta/", views.postal_service, name="postal-service"),
]

dragon/urls.py
from django.urls import path

from . import views

app_name = "dragon"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("aktuality/", views.news, name="news"),
    path("level-system/", views.levelsystem, name="levelsystem"),
    path("email-test/", views.emailtest, name="emailtest"),
    path("uzivatele/", views.users, name="users"),
    path("uzivatele/<int:user_id>/zablokovat/", views.user_ban, name="user-ban"),
    path("uzivatele/<int:user_id>/odblokovat/", views.user_unban, name="user-unban"),
]

graveyard/urls.py
from graveyard.settings.base import INSTALLED_APPS
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ddcz.urls", namespace="ddcz")),
    path("admin/", admin.site.urls),
    path("sprava/", include("dragon.urls", namespace="dragon")),
]

if settings.DEBUG and "debug_toolbar" in INSTALLED_APPS:
    import debug_toolbar

    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

dragon/models.py
# Create your models here.

dragon/forms/dashboard.py
from enum import Enum


class FormTypes(Enum):
    REGISTRATIONS = "registrations"


FormTypes.do_not_call_in_templates = True

ddcz/views/news.py
from datetime import timedelta
import logging

from django.core.cache import cache
from django.core.paginator import Paginator
from django.shortcuts import render
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.views.decorators.vary import vary_on_cookie
from django.conf import settings

from ..creations import ApprovalChoices
from ..models import News, CreativePage, CreationComment

logger = logging.getLogger(__name__)

DEFAULT_LIST_SIZE = 10


@require_http_methods(["HEAD", "GET"])
@vary_on_cookie
def list(request):
    page = request.GET.get("z_s", 1)
    cache_key = "info:news:list"
    news = None

    if page == 1:
        news = cache.get(cache_key)

    if not news:
        news_list = News.objects.order_by("-date")
        paginator = Paginator(news_list, DEFAULT_LIST_SIZE)
        news = paginator.get_page(page)

        if page == 1:
            cache.set(cache_key, news)

    return render(request, "news/list.html", {"news": news})


@require_http_methods(["HEAD", "GET"])
@vary_on_cookie
def newsfeed(request):
    cached = cache.get(settings.NEWSFEED_CACHE_KEY)
    if cached:
        articles = cached["articles"]
        comments = cached["comments"]
    else:
        min_date = timezone.now() - timedelta(
            weeks=settings.NEWSFEED_OLDEST_ARTICLE_INTERVAL_WEEKS
        )
        pages = CreativePage.get_all_models()

        # This could have been a simple list comprehension. But for a reason unknown to me,
        # list(queryset) returns 'QuerySet' object has no attribute 'method', whereas iterating
        # over it works fine, as well as [a for a in queryset] list comprehension
        # Maybe try out again once we upgrade to newest Django
        articles = []
        for page in pages:
            model = page["model"]
            query = model.objects.filter(
                is_published=ApprovalChoices.APPROVED.value, published__gte=min_date
            ).order_by("-published")
            if model.__name__ == "CommonArticle":
                query = query.filter(creative_page_slug=page["page"].slug)
            query = query[0 : settings.NEWSFEED_MAX_CREATIONS]
            for creation in query:
                creation.creative_page = page["page"]
                articles.append(creation)
        articles.sort(key=lambda article: article.published, reverse=True)

        comments = CreationComment.objects.all().order_by("-date")[
            0 : settings.NEWSFEED_MAX_COMMENTS
        ]
        # FIXME: This should be resolvable via GenericRelation once we migrate to it
        page_slug_map = {page["page"].slug: page for page in pages}
        for comment in comments:
            comment_model = page_slug_map[comment.foreign_table]["model"]
            try:
                comment.creation = comment_model.objects.get(pk=comment.foreign_id)
                comment.creation.creative_page = page_slug_map[comment.foreign_table][
                    "page"
                ]
            except comment_model.DoesNotExist:
                logger.exception(
                    f"Can't look up creation for comment {comment.pk} for model {comment_model}"
                )

        cache.set(
            settings.NEWSFEED_CACHE_KEY,
            {"articles": articles, "comments": comments},
            timeout=settings.NEWSFEED_CACHE_INTERVAL,
        )

    return render(
        request, "news/newsfeed.html", {"articles": articles, "comments": comments}
    )

ddcz/views/users.py
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage
from django.core.paginator import Paginator
from django.db.models import F
from django.http import (
    HttpResponseRedirect,
    HttpResponseBadRequest,
)
from django.shortcuts import render, get_object_or_404
from django.urls import resolve, Resolver404
from django.views.decorators.http import require_http_methods

from ..forms.user_settings import PersonalSettingsForm
from ..text import misencode
from ..models import (
    Author,
    UserProfile,
    Rune,
    LEVEL_DESCRIPTIONS,
)

DEFAULT_USER_LIST_SIZE = 50
VALID_SKINS = ["light", "dark", "historic"]


@require_http_methods(["HEAD", "GET"])
def users_list(request):
    # TODO: Displaying newbies & mentats
    # Original query:
    #    $vysledek = MySQL_Query("SELECT a.id, a.nick_uzivatele, a.email_uzivatele, a.vypsat_udaje, a.level $co_vypsat, b.locked as mentat_id, c.newbie_id
    #             FROM uzivatele a left outer join mentat_newbie b
    #                ON (a.id = b.mentat_id) and (b.newbie_id = 0)
    #                left outer join mentat_newbie c
    #                ON (a.id = c.newbie_id) and (c.mentat_id = 0) and (c.locked='0')
    #                ".
    #                $podminka."
    #             ORDER BY ".AddSlashes($ord)." ".AddSlashes($j_ord)." ".addslashes($limit));
    # users = (
    #     UserProfile.objects.filter(  # .all()
    #         Q(newbies__locked="0", newbies__mentat_id=0)
    #         | Q(mentats__locked="1", mentats__newbie_id=0)
    #     )  # .annotate(id_count=Count("id"))
    #     .order_by("-pospristup")
    # )
    # print(str(users.query))
    searched_nick = request.GET.get("nick", None)
    search_limited = False

    if searched_nick:
        if len(searched_nick) <= 3:
            users = UserProfile.objects.filter(nick=misencode(searched_nick)).order_by(
                "nick"
            )
            search_limited = True
        else:
            users = UserProfile.objects.filter(
                nick__icontains=misencode(searched_nick)
            ).order_by("nick")
    else:
        users = UserProfile.objects.all().order_by(
            F("last_login").desc(nulls_last=True)
        )

    paginator = Paginator(users, DEFAULT_USER_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    users = paginator.get_page(page)

    return render(
        request,
        "users/list.html",
        {
            "users": users,
            "searched_nick": searched_nick or "",
            "search_limited": search_limited,
        },
    )


@require_http_methods(["HEAD", "GET"])
def user_profile(request, user_profile_id, nick_slug):
    user_profile = get_object_or_404(UserProfile, id=user_profile_id)
    try:
        creations = Author.objects.get(user=user_profile).get_all_creations()
    except Author.DoesNotExist:
        creations = False

    description = LEVEL_DESCRIPTIONS["0"]
    if user_profile.level in LEVEL_DESCRIPTIONS:
        description = LEVEL_DESCRIPTIONS[user_profile.level]

    level_stars = {
        level: staticfiles_storage.url(
            f"skins/{request.session.get('skin', 'light')}/img/star-level-{level}.svg"
        )
        for level in LEVEL_DESCRIPTIONS
    }

    return render(
        request,
        "users/detail.html",
        {
            "profile": user_profile,
            "permission": user_profile.public_listing_permissions,
            "creations": creations,
            "level_stars": level_stars,
            "level_description": description,
            "runes": Rune.objects.filter(receiver_id=user_profile.id).order_by("-date"),
        },
    )


@require_http_methods(["HEAD", "GET"])
def change_skin(request):
    new_skin = request.GET.get("skin", "light")
    if new_skin not in VALID_SKINS:
        return HttpResponseBadRequest("Nerozpoznán skin, který bych mohl nastavit.")
    request.session["skin"] = new_skin

    try:
        redirect_url = request.GET.get("redirect", "/")
        resolve(redirect_url)
    except Resolver404:
        redirect_url = "/"

    return HttpResponseRedirect(redirect_url)


@login_required
@require_http_methods(["HEAD", "GET", "POST"])
def user_settings(request):
    user_profile = request.user.profile
    saved = False

    if request.method == "POST":
        form = PersonalSettingsForm(request.POST)
        if form.is_valid():
            form.save_to_user_profile(user_profile)
            saved = True
            form = PersonalSettingsForm.from_user_profile(user_profile)
    else:
        form = PersonalSettingsForm.from_user_profile(user_profile)

    return render(
        request,
        "users/settings.html",
        {
            "form": form,
            "saved": saved,
            "user_email": user_profile.email,
        },
    )

dragon/templates/base.html
{% load static %}
<html>
    <head>
        <title>Redaktor {{ user.username }} [redakční systém serveru DraciDoupe.cz]</title>
        <meta charset="utf-8">
        <meta name="robots" content="noindex,nofollow">
        <link rel="stylesheet" href="{% static 'dragon/main.css' %}">
        <link rel="alternate" type="application/rss+xml" href="{% url 'ddcz:feed-phorum' %}" title="Komentáře ve fóru">
        <link rel="alternate" type="application/rss+xml" href="{% url 'ddcz:feed-complete' %}" title="Všechny novinky">
    </head>
    <body lang="cs" data-logged-in="{% if user.is_authenticated %}1{% else %}0{% endif %}">
        <header>
            <h1 class="logo"><a href="{% url 'dragon:dashboard' %}" rel="home"><img src="{% static 'dragon/img/logo.gif' %}" alt="Redakční Systém DraciDoupe.cz"></a></h1>
        </header>
        <div id="app" class="flex">
            <main>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
                {% block content %}{% endblock %}
            </main>

            <nav class="menu">
                <ul>
                    <li><a href="{% url 'dragon:dashboard' %}">Úvod</a></li>
                    <li><a href="{% url 'dragon:news' %}">Aktuality</a></li>
                    <li><a href="{% url 'dragon:users' %}">Uživatelé</a></li>

                    {% if user.is_superuser %}
                        <li><a href="{% url 'dragon:levelsystem' %}">Levelsystém</a></li>
                        <li><a href="{% url 'dragon:emailtest' %}">Test e-mailu</a></li>
                    {% endif %}
                </ul>
            </nav>
            </div>
        <div id="footer">
            © 2002&mdash;2018 & 2021 autorem redakčního systému je Almad, na nějž se stále obracejte v případě nouze :-)
        </div>
    </body>
</html>

dragon/templates/dashboard.html
{% extends 'base.html' %}
{% load html %}
{% load creations %}
{{% block content %}
    <h1>Přehled {{ approval }}</h1>

    {% for user in registrations %}
        {% if forloop.first %}
            <h2>Uživatelé čekající na schválení</h2>

            <table>
            <tr>
                <th>Dne</th>
                <th>Přezdívka</th>
                <th>E-mail</th>
                <th>Jméno</th>
                <th>Pohlaví</th>
                <th>Podporovatelé</th>
                {% comment %} <th>Popis</th> {% endcomment %}
                <th>Akce</th>
            </tr>
        {% endif %}
            <tr>
                <td>{{ user.registration_date | articleTime }}</td>
                <td>{{ user.nick }} ({{ user.salutation }})</td>
                <td>{{ user.email }}</td>
                <td>{{ user.name_given }} {{ user.name_family }}</td>
                <td>{{ user.gender }}</td>
                <td>
                    {% if user.patron %}
                        Patron: {{ user.patron }}
                        Přímluva: {{ user.supporters }}
                    {% else %}
                        Nikdo
                    {% endif %}
                </td>
                {% comment %} <td><pre>{{ user.description }}</pre></td> {% endcomment %}
                <td>
                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="awaiting_registration_id" value="{{ user.id }}">
                        <input type="hidden" name="form_type" value="{{ FormTypes.REGISTRATIONS.value }}">
                        <textarea name="message" placeholder="Dodatečná zpráva pro uživatele"></textarea><br>
                        <input type="submit" name="submission_type" value="{{ RegistrationRequestApproval.APPROVE.value }}"><br>
                        <input type="submit" name="submission_type" value="{{ RegistrationRequestApproval.REJECT.value }}">
                    </form>
                </td>
            </tr>
        {% if forloop.last %}
            </table>
        {% endif %}
    {% endfor %}
{% endblock %}

dragon/templates/emailtest.html
{% extends 'base.html' %}
{% load html %}
{% block content %}
    <h1>Test e-mailu</h1>

    <p>Na této stránce je možné otestovat, zda funguje služba na posílání emailů. Stisknutím tlačítka níže pošlete testovaci e-mail na svoji vlastní adresu.</p>
    <p>Pro zjištění přičin problémů je potřeba se podívat na <a href="https://app.eu.mailgun.com/app/dashboard">dashboard používané služby</a> a nebo <a href="https://dracidoupe.slack.com/archives/C029JA38AAV">na serverové logy</a>.</p>

    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Odeslat testovací email">
    </form>
{% endblock %}

dragon/templates/news.html
{% extends 'base.html' %}
{% load html %}
{% block content %}
    <h1>Aktuality</h1>

    <p>Zde je možné posílat aktuality. Používejte s rozvahou. Odeslané e-maily mohou vývojáři <a href="https://app.eu.mailgun.com/app/dashboard">ladit v Mailgunu</a>.</p>
    <p>Pro editaci a administrátorskou správu aktualit použijte <a href="/admin/ddcz/news/">příslušnou stránku v Django adminu</a>.</p>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Přidat novou aktualitu">
    </form>
{% endblock %}

dragon/templates/users.html
{% extends 'base.html' %}
{% block content %}
    <h1>Správa uživatelů</h1>

    <form method="get" action="">
        <label for="nick">Vyhledat uživatele podle nicku:</label>
        <input type="text" name="nick" id="nick" value="{{ search_query }}" size="25" />
        <input type="submit" value="Vyhledat" />
    </form>

    {% if searched_user %}
        <h2>Nalezený uživatel</h2>
        <table>
            <tr>
                <th>Nick</th>
                <td>{{ searched_user.nick }}</td>
            </tr>
            <tr>
                <th>ID</th>
                <td>{{ searched_user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ searched_user.email }}</td>
            </tr>
            <tr>
                <th>Jméno</th>
                <td>{{ searched_user.name_given }} {{ searched_user.name_family }}</td>
            </tr>
            <tr>
                <th>Pohlaví</th>
                <td>{{ searched_user.gender }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>
                    {% if searched_user.status == "1" %}
                        <strong style="color: red;">Zablokován</strong>
                    {% else %}
                        Aktivní ({{ searched_user.status }})
                    {% endif %}
                </td>
            </tr>
            <tr>
                <th>Popis</th>
                <td>{{ searched_user.description_raw }}</td>
            </tr>
            <tr>
                <th>Reputace</th>
                <td>{{ searched_user.reputation }} (k dispozici: {{ searched_user.reputation_available }})</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ searched_user.level }}</td>
            </tr>
        </table>

        <h3>Akce</h3>
        {% if searched_user.status == "1" %}
            <form method="post" action="{% url 'dragon:user-unban' searched_user.id %}" style="display: inline;">
                {% csrf_token %}
                <input type="submit" value="Odblokovat uživatele" />
            </form>
        {% else %}
            <form method="post" action="{% url 'dragon:user-ban' searched_user.id %}" style="display: inline;">
                {% csrf_token %}
                <input type="submit" value="Zablokovat uživatele" onclick="return confirm('Opravdu chcete zablokovat uživatele {{ searched_user.nick }}?');" />
            </form>
        {% endif %}
    {% endif %}
{% endblock %}