ddcz/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.generic.base import RedirectView, TemplateView
from django.views.decorators.cache import cache_page

from .feeds import PhorumFeed, CompleteNewsFeed
from . import views
from .views import news, tavern, misc, email
from .views.legacy import legacy_router, print_legacy_router

app_name = "ddcz"

urlpatterns = [
    path("", RedirectView.as_view(url="aktuality/", permanent=False)),
    ### Legacy redirects from stare.dracidoupe.cz
    path("index.php", legacy_router, name="legacy-router"),
    re_path(
        "code/(?P<page_category>[a-zA-Z0-9_-]+)/(?P<page_category_second>[a-zA-Z0-9_-]+)_tisk.php",
        print_legacy_router,
        name="legacy-router-print",
    ),
    re_path(
        r"^ikonky/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.USER_ICON_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-icons",
    ),
    re_path(
        r"^fotogalerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-photogallery",
    ),
    re_path(
        r"^galerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-gallery",
    ),
    # It's gone, Dave
    re_path(r"^(moudrasova|img|static|skiny|chat)/", RedirectView.as_view()),
    ### Common pages for bots etc.
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("staticfiles/robots.txt", RedirectView.as_view(url="/robots.txt")),
    path(
        "ads.txt",
        TemplateView.as_view(template_name="ads.txt", content_type="text/plain"),
    ),
    path(
        ".well-known/security.txt",
        TemplateView.as_view(template_name="security.txt", content_type="text/plain"),
    ),
    # Prefetch for Google Chrome
    # Courtesy of https://webmasters.stackexchange.com/a/139570
    path(
        ".well-known/traffic-advice",
        TemplateView.as_view(
            template_name="traffic-advice.json",
            content_type="application/trafficadvice+json",
        ),
    ),
    ### Creations and Creative Pages
    path(
        "rubriky/<creative_page_slug>/", views.creative_page_list, name="creation-list"
    ),
    path(
        "rubriky/<creative_page_slug>/koncepce/",
        views.creative_page_concept,
        name="creative-page-concept",
    ),
    path(
        "rubriky/<creative_page_slug>/kontrola-html/",
        views.creative_page_html_check,
        name="creative_page_html_check",
    ),
    # path(
    #     "rubriky/<creative_page_slug>/<int:creation_id>-<creation_slug>/",
    #     views.creation_detail,
    #     name="creation-detail",
    # ),
    re_path(
        "^rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/$",
        views.creation_detail,
        name="creation-detail",
    ),
    re_path(
        "rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/obr_pris/(?P<image_path>.+)",  # /(?P<image_path_name>\w+)",
        views.creation_detail_image,
        name="creation-detail-image",
    ),
    re_path(
        r"obr_pris/(?P<image_path>[\w\/]+\.[\w]+)",
        views.creation_detail_image_legacy,
        name="creation-legacy-detail-image",
    ),
    # Standard list and detail are under creation pages above,
    # Those are for executing redirect to download/quest location
    path("download/<int:download_id>/", views.download_file, name="download-file"),
    path(
        "dobrodruzstvi/<int:quest_id>/",
        views.quest_view_redirect,
        name="quest-view-legacy-redirect",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)-(?P<quest_slug>[a-zA-Z0-9_-]+)/$",
        views.quest_view_redirect,
        name="quest-view",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)(-)?(?P<quest_slug>[a-zA-Z0-9_-]+)?/(?P<leftover>.*)$",
        views.quest_view_redirect_rest,
        name="quest-view-rest",
    ),
    ### User handling
    path("uzivatele/", views.users_list, name="users-list"),
    path("uzivatel/prihlaseni/", views.login, name="login-action"),
    path("registrace/", views.sign_up, name="sign-up"),
    path("uzivatel/odhlaseni/", views.logout, name="logout-action"),
    path(
        "uzivatel/reset-hesla/",
        views.PasswordResetView.as_view(),
        name="password-reset",
    ),
    path(
        "uzivatel/reset-hesla/hotovo/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "uzivatel/zmena-hesla/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password-change",
    ),
    path(
        "uzivatel/zmena-hesla/hotovo/",
        views.PasswordResetCompleteView.as_view(),
        name="password-change-done",
    ),
    path(
        "uzivatel/<int:user_profile_id>-<nick_slug>/",
        views.user_profile,
        name="user-detail",
    ),
    path("autor/<int:author_id>-<slug>/", views.author_detail, name="author-detail"),
    ### User settings
    path("nastaveni/zmena-skinu/", views.change_skin, name="change-skin"),
    path("nastaveni/", views.user_settings, name="user-settings"),
    ### Emails
    path(
        "e-mail/antispam/potvrzeni/",
        TemplateView.as_view(template_name="emails/unsub-confirm.html"),
        name="email-antispam-confirm",
    ),
    path(
        "e-mail/antispam/<email_base64>-<unsub_token>/",
        email.antispam,
        name="email-antispam",
    ),
    ### Info sites
    path("aktuality/", news.list, name="news"),
    path("novinky/", news.newsfeed, name="newsfeed"),
    path("seznamka/", views.dating, name="dating"),
    path("seznamka/pridat/", views.misc.dating_create, name="dating-create"),
    path("inzerce/", views.market, name="market"),
    path("inzerce/pridej/", views.market_create, name="market-create"),
    path("inzerce/smaz/<int:id>/", views.market_delete, name="market-delete"),
    path("linky/", views.links, name="links-list"),
    ### Discussions & Tavern
    path("forum/", views.phorum, name="phorum-list"),
    ### RSS cheat: pretend we have unique links for items. We may in the future.
    path(
        "forum/<int:comment_id>/",
        RedirectView.as_view(url="/forum/", permanent=False),
        name="phorum-item",
    ),
    path("putyka/", tavern.list_tables, name="tavern-list"),
    path(
        "putyka/stul/<int:tavern_table_id>/prispevky/",
        tavern.table_posts,
        name="tavern-posts",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/nastenka/",
        tavern.notice_board,
        name="tavern-notice-board",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/administrace/",
        tavern.table_administration,
        name="tavern-table-admin",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/oblibit/",
        tavern.table_bookmark,
        name="tavern-bookmark",
    ),
    ### RSS & Feeds
    path(
        "rss/forum/",
        cache_page(settings.RSS_CACHE_INTERVAL)(PhorumFeed()),
        name="feed-phorum",
    ),
    path("rss/forum.xml", RedirectView.as_view(url="/rss/forum/", permanent=True)),
    path(
        "rss/novinky/",
        cache_page(settings.RSS_CACHE_INTERVAL)(CompleteNewsFeed()),
        name="feed-complete",
    ),
    path("rss/novinky.xml", RedirectView.as_view(url="/rss/novinky/", permanent=True)),
    ### Static Editorial Pages
    ### Would be easier to give them /static prefix, but it makes for ugly URL
    path(
        "co-je-draci-doupe/",
        views.editor_article,
        name="about-drd",
        kwargs={"slug": "co-je-draci-doupe"},
    ),
    path(
        "draci-manual/",
        views.editor_article,
        name="website-manual",
        kwargs={"slug": "draci-manual"},
    ),
    path(
        "otazky-a-odpovedi/",
        views.editor_article,
        name="faq",
        kwargs={"slug": "otazky-a-odpovedi"},
    ),
    path(
        "tvurci-a-redakce/",
        misc.web_authors_and_editors,
        name="web-authors-and-editors",
    ),
    path("posta/", views.postal_service, name="postal-service"),
]

graveyard/urls.py
from graveyard.settings.base import INSTALLED_APPS
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ddcz.urls", namespace="ddcz")),
    path("admin/", admin.site.urls),
    path("sprava/", include("dragon.urls", namespace="dragon")),
]

if settings.DEBUG and "debug_toolbar" in INSTALLED_APPS:
    import debug_toolbar

    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

ddcz/forms.py
import logging

from django import forms
from django.contrib.auth import forms as authforms

from .models import UserProfile

logger = logging.getLogger(__name__)


class LoginForm(forms.Form):
    nick = forms.CharField(label="Nick", max_length=20)
    password = forms.CharField(label="Heslo", max_length=50, widget=forms.PasswordInput)


class PasswordResetForm(authforms.PasswordResetForm):
    def get_users(self, email):
        """Given an email, return matching user(s) who should receive a reset.
        This is overridem from original form to use UserProfile instead of standard
        user model since that is normative for email storage.
        """

        user_profiles = UserProfile.objects.filter(email_uzivatele__iexact=email)

        users = tuple(
            list(
                up.user
                for up in user_profiles
                if up.user.has_usable_password() and up.user.is_active
            )
        )

        logger.info(
            "Selected users for password reset: %s"
            % ", ".join([str(u.pk) for u in users])
        )

        return users

ddcz/forms/settings.py
from time import time
from enum import Enum

from django import forms
from django.forms import ModelForm
from django.http import request
from django.utils.safestring import mark_safe

from ..models import UserProfile


class SettingsForm(ModelForm):

    MIN_AGE = 13

    class SexChoices(Enum):
        M = "mužské"
        F = "ženské"

    class VisibilityChoices(Enum):
        FALSE = "Nezobrazovat na profilu"
        TRUE = "Zobrazit pro všechny"

    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(
            attrs={"placeholder": "Zadej emailovou adresu", "id": "email"}
        ),
    )

    gender = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in SexChoices],
    )

    age = forms.IntegerField(
        label="",
        widget=forms.NumberInput(
            attrs={"placeholder": "Tvůj věk", "id": "age", "min": MIN_AGE, "max": 150}
        ),
    )

    name_given_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    name_family_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    email_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    gender_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    age_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    shire_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    icq_visibility = forms.ChoiceField(
        label="",
        widget=forms.Select(),
        choices=[(tag.name, tag.value) for tag in VisibilityChoices],
    )

    description_raw = forms.CharField(required=False, label="", widget=forms.Textarea())

    class Meta:
        model = UserProfile
        fields = [
            "email",
            "name_given",
            "name_family",
            "age",
            "shire",
            "gender",
            "icq",
            "description_raw",
        ]

ddcz/forms/user_settings.py
from enum import Enum

from django import forms


SHIRE_CHOICES = [
    ("", "-- Vyberte kraj --"),
    ("Praha", "Praha"),
    ("Středočeský kraj", "Středočeský kraj"),
    ("Budějovický kraj", "Budějovický kraj"),
    ("Plzeňský kraj", "Plzeňský kraj"),
    ("Karlovarský kraj", "Karlovarský kraj"),
    ("Ústecký kraj", "Ústecký kraj"),
    ("Liberecký kraj", "Liberecký kraj"),
    ("Královéhradecký kraj", "Královéhradecký kraj"),
    ("Pardubický kraj", "Pardubický kraj"),
    ("Kraj Vysočina", "Kraj Vysočina"),
    ("Brněnský kraj", "Brněnský kraj"),
    ("Olomoucký kraj", "Olomoucký kraj"),
    ("Moravskoslezský kraj", "Moravskoslezský kraj"),
    ("Zlínský kraj", "Zlínský kraj"),
    ("Bratislavský kraj", "Bratislavský kraj"),
    ("Trnavský kraj", "Trnavský kraj"),
    ("Trenčiansky kraj", "Trenčiansky kraj"),
    ("Nitriansky kraj", "Nitriansky kraj"),
    ("Žilinský kraj", "Žilinský kraj"),
    ("Banskobystrický kraj", "Banskobystrický kraj"),
    ("Prešovský kraj", "Prešovský kraj"),
    ("Košický kraj", "Košický kraj"),
]


class GenderChoices(Enum):
    M = "Muž"
    F = "Žena"


class PersonalSettingsForm(forms.Form):
    name_given = forms.CharField(
        label="Jméno",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-input"}),
    )

    name_family = forms.CharField(
        label="Příjmení",
        max_length=20,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-input"}),
    )

    gender = forms.ChoiceField(
        label="Pohlaví",
        choices=[(tag.name, tag.value) for tag in GenderChoices],
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )

    shire = forms.ChoiceField(
        label="Kraj bydliště",
        choices=SHIRE_CHOICES,
        required=False,
        widget=forms.Select(attrs={"class": "form-select"}),
    )

    description = forms.CharField(
        label="Popis",
        max_length=255,
        required=False,
        widget=forms.Textarea(
            attrs={
                "class": "form-textarea",
                "rows": 5,
                "cols": 60,
            }
        ),
        help_text="Popis slouží k lepší identifikaci uživatele. Máte k dispozici asi 255 znaků.",
    )

    show_name_given = forms.BooleanField(
        label="Zobrazit jméno",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    show_name_family = forms.BooleanField(
        label="Zobrazit příjmení",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    show_email = forms.BooleanField(
        label="Zobrazit e-mail",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    show_gender = forms.BooleanField(
        label="Zobrazit pohlaví",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    show_age = forms.BooleanField(
        label="Zobrazit věk",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    show_shire = forms.BooleanField(
        label="Zobrazit kraj",
        required=False,
        widget=forms.CheckboxInput(attrs={"class": "form-checkbox"}),
    )

    @classmethod
    def from_user_profile(cls, user_profile):
        permissions = user_profile.public_listing_permissions
        gender_value = ""
        if user_profile.gender in ["Muž", "Mu\x9e"]:
            gender_value = "M"
        elif user_profile.gender in ["Žena", "®ena"]:
            gender_value = "F"

        return cls(
            initial={
                "name_given": user_profile.name_given,
                "name_family": user_profile.name_family,
                "gender": gender_value,
                "shire": user_profile.shire or "",
                "description": user_profile.description_raw or "",
                "show_name_given": permissions["name_given"],
                "show_name_family": permissions["name_family"],
                "show_email": permissions["email"],
                "show_gender": permissions["gender"],
                "show_age": permissions["age"],
                "show_shire": permissions["shire"],
            }
        )

    def save_to_user_profile(self, user_profile):
        user_profile.name_given = self.cleaned_data["name_given"]
        user_profile.name_family = self.cleaned_data["name_family"]

        gender_map = {"M": "Muž", "F": "Žena"}
        user_profile.gender = gender_map.get(self.cleaned_data["gender"], "")

        user_profile.shire = self.cleaned_data["shire"]
        user_profile.description_raw = self.cleaned_data["description"]

        permissions = user_profile.public_listing_permissions
        new_permissions = [
            "1" if self.cleaned_data["show_name_given"] else "",
            "1" if self.cleaned_data["show_name_family"] else "",
            "1" if self.cleaned_data["show_email"] else "",
            "1" if permissions.get("icq", False) else "",
            "1" if self.cleaned_data["show_gender"] else "",
            "1" if self.cleaned_data["show_age"] else "",
            "1" if self.cleaned_data["show_shire"] else "",
            "1" if permissions.get("birthday", False) else "",
        ]
        user_profile.pii_display_permissions = ",".join(new_permissions)

        user_profile.save()

ddcz/templates/users/awaiting-registrations.html
{% extends 'public.html' %}
{% load datetime %}
{% block content %}

<h1 class="page-heading">Dračí líheň</h1>
<p>
    
</p>

{% if awaiting %}
<table id="awaiting_registration">    
    <tr>
        <th>Dračí vejce</th>
        <th>Čas líhnutí</th>
        <th>Očekávané vylíhnutí</th>
        <th>Dračí chovatel</th>
        {% if user.userprofile.level in dragon_confirming_levels %}
        <th>Měští úředníci</th>
        {% endif %}
    </tr>
    {% for registration in registrations %}
    <tr>
        <td>{{ registration.nick }}</td>
        <td>{{ registration.waiting_time | timestamp_to_difference }}</td>
        <td>{{ registration.expected_approval_time | timestamp_to_datetime }}</td>
        <td>            
            {% if registration.patron is not 0 %}
            {{ registration.patron_name }}
            {% elif user.userprofile is not null %}
            
            {% endif %}
        </td>
        <td>
            {% if user.userprofile.level in dragon_confirming_levels %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="{{ dragon_keeper }}" value="{{ registration.id }}">
                <button type="submit" disabled>Vylíhnutí vejce</button>
            </form>
            {% endif %}            
        </td>
    </tr>
    {% endfor %}    
</table>
{% else %}
<p><b>Aktuálně se nelíhne žádný mladý dráček.</b></p>
{% endif %}    
{% endblock %}

ddcz/templates/users/level-star.html
<img class="star_level" src="{{ star_image_url }}" alt="Uživatel úrovně {{ level }}">

ddcz/templates/users/list.html
{% extends 'public.html' %}
{% load html %}
{% load pages %}
{% load users %}

{% block content %}
<div class="user-list">
    <h1 class="page-heading">Uživatelé</h1>

    <p>Kliknutím na nick uživatele nebo vepsáním nicku nebo ID do formuláře se zobrazí jeho podrobnosti.</p>

    <form method="get" action="{% url "ddcz:users-list" %}">
        Nick: <input type="text" name="nick" value="{{ searched_nick }}">
        <input type="submit" value="Najít">
    </form>

    {% if search_limited %}
        <p class="message__warning">Vyhledáváný nick je příliš krátký. U dorazů kratších, než tři znaky jsou zobrazeny pouze nicky stejného znění.</p>
    {% endif %}

    {% pagination users %}
    <br>

    <table class="user-list__table">
    <tr>
        <th>Nick</th>
        <th>Level</th>
        {% if user.is_authenticated %}
            <th>E-mail</th>
        {% endif %}
        <th>Popis</th>
    </tr>

    {% for profile in users %}
        <tr>
            <td><a href="{{ profile.profile_url }}">{{ profile.nick }}</a></td>
            <td>{% level_star profile skin %}</td>
            {% if user.is_authenticated %}
                <td>
                    {% if profile.show_email %}
                        <a href="mailto:{{ profile.email }}" rel="external">{{ profile.email }}</a>
                    {% else %}
                        <span title="Uživatel{% if profile.is_female %}ka{% endif %} se rozhodl{% if profile.is_female %}a{% endif %} e-mail nezveřejnit">---</span>
                    {% endif %}
                </td>
            {% endif %}
            <td>{{ profile.description | render_html | safe }}</td>
        </tr>
    {% endfor %}

    </table>

    {% pagination users %}

</div>

{% endblock %}

ddcz/templates/users/password-change-done.html
{% extends 'public.html' %}
{% load html %}
{% block content %}
<div id="page-password-change-done">
    <h1 class="page-heading">Heslo změněno</h1>
    <p>Heslo změněno. Dobrá práce!</p>
</div>
{% endblock %}

ddcz/templates/users/password-change.html
{% extends 'public.html' %}
{% load html %}
{% block content %}
<div id="page-password-change">
    <h1 class="page-heading">Změna hesla</h1>

    {% if validlink %}

        <form method="post">
            {% csrf_token %}
            <input style="display: none;" autocomplete="username" value="{{ form.user.username }}">
            {{ form.as_ul }}
            <br>
            <input type="submit" value="Zmeň heslo">
        </form>

    {% else %}

    <p>Něco je špatně s odkazem, kterým jste se sem dostali. Prosím, <a href="{% url 'ddcz:password-reset' %}">vyžádejte si link znovu</a>.</p>

    {% endif %}
</div>
{% endblock %}

ddcz/templates/users/password-reset-done.html
{% extends 'public.html' %}
{% load html %}
{% block content %}
<div id="page-password-reset-done">
    <h1 class="page-heading">Reset hesla</h1>
    <p>Pokud je e-mail platný, odeslali jsme na něj odkaz pro reset hesla.</p>
</div>
{% endblock %}

ddcz/templates/users/password-reset-email.html
{% autoescape off %}

Ahoj!

Byl jsem pověřen, abych donesl zprávu o žádosti o změnu hesla. Pokud jsi o ni požádal ty, navštiv následující odkaz pro dokončení změny. 

{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'ddcz:password-change' uidb64=uid token=token %}
{% endblock %}

Doufám, že se brzy uvidíme!

Listonoš serveru DraciDoupe.cz

{% endautoescape %}

ddcz/templates/users/password-reset.html
{% extends 'public.html' %}
{% load html %}
{% block content %}
<div id="page-password-reset">
    <h1 class="page-heading">Reset hesla</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <br>
        <input type="submit" value="Pošli e-mail s adresou">
    </form>

</div>
{% endblock %}

ddcz/templates/users/settings.html
{% extends "public.html" %}

{% block content %}
<h1 class="page-heading">Nastavení</h1>

<nav class="settings-nav">
    <strong><a href="{% url 'ddcz:user-settings' %}">Osobní údaje</a></strong>
</nav>

<section class="settings-section">
    <h2>Osobní údaje</h2>

    {% if saved %}
        <div class="message success">
            <strong>Uloženo!</strong>
        </div>
    {% endif %}

    {% if form.errors %}
        <div class="message error">
            {% for field in form %}
                {% for error in field.errors %}
                    <p><strong>{{ field.label }}:</strong> {{ error }}</p>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <p><strong>{{ error }}</strong></p>
            {% endfor %}
        </div>
    {% endif %}

    <form method="post" action="{% url 'ddcz:user-settings' %}">
        {% csrf_token %}

        <table class="settings-form">
            <tbody>
                <tr>
                    <th colspan="3">Základní údaje</th>
                </tr>
                <tr>
                    <td><label for="id_name_given">{{ form.name_given.label }}:</label></td>
                    <td>{{ form.name_given }}</td>
                    <td>{{ form.show_name_given }} Zobrazit ve výpisu</td>
                </tr>
                <tr>
                    <td><label for="id_name_family">{{ form.name_family.label }}:</label></td>
                    <td>{{ form.name_family }}</td>
                    <td>{{ form.show_name_family }} Zobrazit ve výpisu</td>
                </tr>
                <tr>
                    <td><label>E-mail:</label></td>
                    <td>{{ user_email }}</td>
                    <td>{{ form.show_email }} Zobrazit ve výpisu</td>
                </tr>
                <tr>
                    <td><label for="id_gender">{{ form.gender.label }}:</label></td>
                    <td>{{ form.gender }}</td>
                    <td>{{ form.show_gender }} Zobrazit ve výpisu</td>
                </tr>
                <tr>
                    <td><label for="id_shire">{{ form.shire.label }}:</label></td>
                    <td>{{ form.shire }}</td>
                    <td>{{ form.show_shire }} Zobrazit ve výpisu</td>
                </tr>
                <tr>
                    <td></td>
                    <td></td>
                    <td>{{ form.show_age }} Zobrazit věk ve výpisu</td>
                </tr>
                <tr>
                    <th colspan="3">Popis</th>
                </tr>
                <tr>
                    <td colspan="3">
                        {{ form.description }}
                        <p class="help-text">{{ form.description.help_text }}</p>
                    </td>
                </tr>
            </tbody>
        </table>

        <p>
            <input type="submit" value="Uložit změny">
        </p>
    </form>
</section>

{% endblock %}

ddcz/templates/users/sign_up_after.html
{% extends "public.html" %}

{% block styles %}
<link rel="stylesheet" href="{{ reg_style }}">
{% endblock %}

{% block scripts %}
<script type="module" src="{{ reg_script }}" async></script>
{% endblock %}


{% block content %}            
<h1 class="page-heading">Vítej ve Městě, {{ addressing }}!</h1>
        

<section id="registration_page">    
        <p class="first_paragraph">
            Tvá žádost o vstup do města byla odeslána ke schválení. Nyní vyčkej, až ti na emailovou adresu přijde zpráva od našich redaktorů.
        </p>
</section>


{% endblock %}