ddcz/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.generic.base import RedirectView, TemplateView
from django.views.decorators.cache import cache_page

from .feeds import PhorumFeed, CompleteNewsFeed
from . import views
from .views import news, tavern, misc, email
from .views.legacy import legacy_router, print_legacy_router

app_name = "ddcz"

urlpatterns = [
    path("", RedirectView.as_view(url="aktuality/", permanent=False)),
    ### Legacy redirects from stare.dracidoupe.cz
    path("index.php", legacy_router, name="legacy-router"),
    re_path(
        "code/(?P<page_category>[a-zA-Z0-9_-]+)/(?P<page_category_second>[a-zA-Z0-9_-]+)_tisk.php",
        print_legacy_router,
        name="legacy-router-print",
    ),
    re_path(
        r"^ikonky/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.USER_ICON_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-icons",
    ),
    re_path(
        r"^fotogalerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-photogallery",
    ),
    re_path(
        r"^galerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-gallery",
    ),
    # It's gone, Dave
    re_path(r"^(moudrasova|img|static|skiny|chat)/", RedirectView.as_view()),
    ### Common pages for bots etc.
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("staticfiles/robots.txt", RedirectView.as_view(url="/robots.txt")),
    path(
        "ads.txt",
        TemplateView.as_view(template_name="ads.txt", content_type="text/plain"),
    ),
    path(
        ".well-known/security.txt",
        TemplateView.as_view(template_name="security.txt", content_type="text/plain"),
    ),
    # Prefetch for Google Chrome
    # Courtesy of https://webmasters.stackexchange.com/a/139570
    path(
        ".well-known/traffic-advice",
        TemplateView.as_view(
            template_name="traffic-advice.json",
            content_type="application/trafficadvice+json",
        ),
    ),
    ### Creations and Creative Pages
    path(
        "rubriky/<creative_page_slug>/", views.creative_page_list, name="creation-list"
    ),
    path(
        "rubriky/<creative_page_slug>/koncepce/",
        views.creative_page_concept,
        name="creative-page-concept",
    ),
    path(
        "rubriky/<creative_page_slug>/kontrola-html/",
        views.creative_page_html_check,
        name="creative_page_html_check",
    ),
    # path(
    #     "rubriky/<creative_page_slug>/<int:creation_id>-<creation_slug>/",
    #     views.creation_detail,
    #     name="creation-detail",
    # ),
    re_path(
        "^rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/$",
        views.creation_detail,
        name="creation-detail",
    ),
    re_path(
        "rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/obr_pris/(?P<image_path>.+)",  # /(?P<image_path_name>\w+)",
        views.creation_detail_image,
        name="creation-detail-image",
    ),
    re_path(
        r"obr_pris/(?P<image_path>[\w\/]+\.[\w]+)",
        views.creation_detail_image_legacy,
        name="creation-legacy-detail-image",
    ),
    # Standard list and detail are under creation pages above,
    # Those are for executing redirect to download/quest location
    path("download/<int:download_id>/", views.download_file, name="download-file"),
    path(
        "dobrodruzstvi/<int:quest_id>/",
        views.quest_view_redirect,
        name="quest-view-legacy-redirect",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)-(?P<quest_slug>[a-zA-Z0-9_-]+)/$",
        views.quest_view_redirect,
        name="quest-view",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)(-)?(?P<quest_slug>[a-zA-Z0-9_-]+)?/(?P<leftover>.*)$",
        views.quest_view_redirect_rest,
        name="quest-view-rest",
    ),
    ### User handling
    path("uzivatele/", views.users_list, name="users-list"),
    path("uzivatel/prihlaseni/", views.login, name="login-action"),
    path("registrace/", views.sign_up, name="sign-up"),
    path("uzivatel/odhlaseni/", views.logout, name="logout-action"),
    path(
        "uzivatel/reset-hesla/",
        views.PasswordResetView.as_view(),
        name="password-reset",
    ),
    path(
        "uzivatel/reset-hesla/hotovo/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "uzivatel/zmena-hesla/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password-change",
    ),
    path(
        "uzivatel/zmena-hesla/hotovo/",
        views.PasswordResetCompleteView.as_view(),
        name="password-change-done",
    ),
    path(
        "uzivatel/<int:user_profile_id>-<nick_slug>/",
        views.user_profile,
        name="user-detail",
    ),
    path("autor/<int:author_id>-<slug>/", views.author_detail, name="author-detail"),
    ### User settings
    path("nastaveni/zmena-skinu/", views.change_skin, name="change-skin"),
    path("nastaveni/", views.user_settings, name="user-settings"),
    ### Emails
    path(
        "e-mail/antispam/potvrzeni/",
        TemplateView.as_view(template_name="emails/unsub-confirm.html"),
        name="email-antispam-confirm",
    ),
    path(
        "e-mail/antispam/<email_base64>-<unsub_token>/",
        email.antispam,
        name="email-antispam",
    ),
    ### Info sites
    path("aktuality/", news.list, name="news"),
    path("novinky/", news.newsfeed, name="newsfeed"),
    path("seznamka/", views.dating, name="dating"),
    path("seznamka/pridat/", views.misc.dating_create, name="dating-create"),
    path("inzerce/", views.market, name="market"),
    path("inzerce/pridej/", views.market_create, name="market-create"),
    path("inzerce/smaz/<int:id>/", views.market_delete, name="market-delete"),
    path("linky/", views.links, name="links-list"),
    ### Discussions & Tavern
    path("forum/", views.phorum, name="phorum-list"),
    ### RSS cheat: pretend we have unique links for items. We may in the future.
    path(
        "forum/<int:comment_id>/",
        RedirectView.as_view(url="/forum/", permanent=False),
        name="phorum-item",
    ),
    path("putyka/", tavern.list_tables, name="tavern-list"),
    path(
        "putyka/stul/<int:tavern_table_id>/prispevky/",
        tavern.table_posts,
        name="tavern-posts",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/nastenka/",
        tavern.notice_board,
        name="tavern-notice-board",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/administrace/",
        tavern.table_administration,
        name="tavern-table-admin",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/oblibit/",
        tavern.table_bookmark,
        name="tavern-bookmark",
    ),
    ### RSS & Feeds
    path(
        "rss/forum/",
        cache_page(settings.RSS_CACHE_INTERVAL)(PhorumFeed()),
        name="feed-phorum",
    ),
    path("rss/forum.xml", RedirectView.as_view(url="/rss/forum/", permanent=True)),
    path(
        "rss/novinky/",
        cache_page(settings.RSS_CACHE_INTERVAL)(CompleteNewsFeed()),
        name="feed-complete",
    ),
    path("rss/novinky.xml", RedirectView.as_view(url="/rss/novinky/", permanent=True)),
    ### Static Editorial Pages
    ### Would be easier to give them /static prefix, but it makes for ugly URL
    path(
        "co-je-draci-doupe/",
        views.editor_article,
        name="about-drd",
        kwargs={"slug": "co-je-draci-doupe"},
    ),
    path(
        "draci-manual/",
        views.editor_article,
        name="website-manual",
        kwargs={"slug": "draci-manual"},
    ),
    path(
        "otazky-a-odpovedi/",
        views.editor_article,
        name="faq",
        kwargs={"slug": "otazky-a-odpovedi"},
    ),
    path(
        "tvurci-a-redakce/",
        misc.web_authors_and_editors,
        name="web-authors-and-editors",
    ),
    path("posta/", views.postal_service, name="postal-service"),
]

graveyard/urls.py
from graveyard.settings.base import INSTALLED_APPS
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ddcz.urls", namespace="ddcz")),
    path("admin/", admin.site.urls),
    path("sprava/", include("dragon.urls", namespace="dragon")),
]

if settings.DEBUG and "debug_toolbar" in INSTALLED_APPS:
    import debug_toolbar

    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

ddcz/forms/commentForms.py
from django import forms
from django.http import HttpResponse
from ..models.used.discussion import Phorum


class PhorumCommentForm(forms.Form):
    text = forms.CharField(
        label="", widget=forms.Textarea(attrs={"class": "comment__textarea"})
    )
    username = forms.HiddenInput()

ddcz/views/comments.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from ..forms.comments import PhorumCommentForm, DeletePhorumCommentForm
from ..text import escape_user_input
from ..models import Phorum, ADD_PHORUM_COMMENT, DELETE_PHORUM_COMMENT


@require_http_methods(["HEAD", "GET", "POST"])
def phorum(request):
    if request.method == "POST" and request.POST["post_type"] and request.user:
        if (
            request.POST["post_type"] == DELETE_PHORUM_COMMENT
            and request.POST["submit"] == "Smazat"
        ):
            try:
                Phorum.objects.get(
                    id=request.POST["post_id"],
                    nickname=request.user.profile.nick,
                ).delete()
            except Phorum.DoesNotExist:
                messages.error(request, "Zprávu se nepodařilo smazat.")
                return HttpResponseRedirect(reverse("ddcz:phorum-list"))

        elif (
            request.POST["post_type"] == ADD_PHORUM_COMMENT
            and request.POST["submit"] == "Přidej"
        ):
            form = PhorumCommentForm(request.POST)
            if form.is_valid():
                Phorum.objects.create(
                    reputation=0,
                    registered_or_ip=1,
                    user=request.user.profile,
                    text=escape_user_input(form.cleaned_data["text"]),
                    nickname=request.user.profile.nick,
                    email=request.user.profile.email,
                )

        return HttpResponseRedirect(reverse("ddcz:phorum-list"))

    default_limit = 20
    discussions = Phorum.objects.all().order_by("-date")

    paginator = Paginator(discussions, default_limit)
    page = request.GET.get("z_s", 1)

    discussions = paginator.get_page(page)

    return render(
        request,
        "discussions/phorum-list.html",
        {
            "discussions": discussions,
            "phorum_comment_form": PhorumCommentForm(),
            "delete_form": DeletePhorumCommentForm(),
        },
    )

ddcz/views/email.py
import logging

from django.http import (
    HttpResponseRedirect,
    HttpResponseBadRequest,
)
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from ..email import validate_unsubscribe_token, blacklist_email
from ..models import EmailSubscriptionAuth

logger = logging.getLogger(__name__)


@require_http_methods(["HEAD", "GET", "POST"])
def antispam(request, email_base64, unsub_token):
    if not email_base64 or not unsub_token:
        return HttpResponseBadRequest("Špatný formát odhlašovacího kódu.")

    try:
        validate_unsubscribe_token(email_base64, unsub_token)
    except EmailSubscriptionAuth.DoesNotExist:
        logger.warning(
            f"User tried to unsubscribe email {email_base64}, but it wasn't found in a database"
        )
        return HttpResponseBadRequest(
            "Tento e-mail není v databázi. Nezměnil jsi ho mezitím v profilu, případně nebyl už zařazen do seznamu zakázaných e-mailů? Byla zaslána zpráva adminům, neb toto by se nemělo stát. "
        )
    else:
        if request.method == "POST":
            blacklist_email(email_base64)
            return HttpResponseRedirect(reverse("ddcz:email-antispam-confirm"))
        else:
            return render(
                request,
                "emails/antispam.html",
                {},
            )

ddcz/views/misc.py
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods

from ..models import (
    Market,
    UserProfile,
    Dating,
    Link,
    EditorArticle,
    MARKET_SECTION_CHOICES,
)
from ..forms.market import MarketForm
from ..forms.dating import DatingForm

DEFAULT_LIST_SIZE = 10


# Get an instance of a logger
logger = logging.getLogger(__name__)


@require_http_methods(["HEAD", "GET"])
def links(request):
    item_list = Link.objects.filter(is_approved="a").order_by("-published")

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "links/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def dating(request):
    item_list = Dating.objects.order_by("-published")

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "dating/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def market(request):
    item_list = Market.objects.order_by("-created")

    section = request.GET.get("sekce", None)
    if section:
        if section not in [i[0] for i in MARKET_SECTION_CHOICES]:
            raise Http404()

        item_list = item_list.filter(group=request.GET.get("sekce"))

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "market/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def editor_article(request, slug):
    article = get_object_or_404(EditorArticle, slug=slug)

    return render(
        request,
        "info/editor-article.html",
        {"article": article},
    )


@require_http_methods(["HEAD", "GET"])
def web_authors_and_editors(request):
    hall_of_fame = [
        {
            "user_profile": UserProfile.objects.get(nick="James Timqui"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Alcator"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Legar"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="deshi"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Igi"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Suk"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Nathaka"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Kamerask"),
            "role": "tribun",
        },
    ]

    return render(
        request,
        "info/web-authors-and-editors.html",
        {
            "tribune": UserProfile.objects.get(pk=settings.TRIBUNE_ID),
            "famous_users": hall_of_fame,
        },
    )


def market_create(request):
    if request.method == "POST":
        form = MarketForm(request.POST)
        if form.is_valid():
            market_item = form.save(commit=False)
            market_item.user_profile = request.ddcz_profile
            form.save()
            return redirect("ddcz:market")
    else:
        form = MarketForm()

    return render(request, "market/create.html", {"form": form})


@login_required
@require_http_methods(["POST"])
def market_delete(request, id):
    market_item = get_object_or_404(Market, id=id)
    if market_item.user_profile == request.ddcz_profile:
        market_item.delete()
    return redirect("ddcz:market")


def dating_create(request):
    if request.method == "POST":
        form = DatingForm(request.POST)
        if form.is_valid():
            dating_item = form.save(commit=False)
            dating_item.user_profile = request.ddcz_profile
            form.save()
            return redirect("ddcz:dating")
    else:
        form = DatingForm()

    return render(request, "dating/create.html", {"form": form})


@login_required
@require_http_methods(["POST"])
def dating_delete(request, id):
    dating_item = get_object_or_404(Dating, id=id)
    if dating_item.user_profile == request.ddcz_profile:
        dating_item.delete()
    return redirect("ddcz:dating")

ddcz/templates/creative-pages/alchemisttool-detail.html
{% extends 'public.html' %}
{% load comments %}
{% load creations %}
{% load html %}
{% block content %}
<div id="page-article-detail">
    <h1 class="page-heading">{{ heading }}</h1>
    <article>
        <header>
            <h2>{{ article.name }}{% creation_rating article.rating skin %}</h2>
            <!-- TODO
            <p>Příprava pro tisk</p>
            -->
            <table>
                <tr>
                    <th>Autor:</th>
                    <td>{% author_display article %}</td>
                </tr>
                <tr>
                    <th>Přidáno:</th>
                    <td><time datetime="{{ article.published | date:"c"  }}">{{ article.published | articleTime }}</time></td>
                </tr>
                <tr>
                    <th>Hlasovalo:</th>
                    <td>{{ article.rater_no }}</td>
                </tr>
            </table>

            <p><span class="label">Skupina:</span> <span class="value">{{ article.group }}</span></p>
            {% if article.magenergy %}
                <p><span class="label">Magenergie:</span> <span class="value">{{ article.magenergy }}</span></p>
              {% endif %}
            {% if article.resources %}
                <p><span class="label">Suroviny:</span> <span class="value">{{ article.resources }}</span></p>
            {% endif %}
            {% if article.base %}
                <p><span class="label">Základ:</span> <span class="value">{{ article.base }}</span></p>
            {% endif %}
            {% if article.discovery %}
                <p><span class="label">Nalezení:</span> <span class="value">{{ article.discovery }}</span></p>
            {% endif %}
            {% if article.duration %}
                <p><span class="label">Trvání:</span> <span class="value">{{ article.duration }}</span></p>
            {% endif %}
            {% if article.crafting %}
                <p><span class="label">Výroba:</span> <span class="value">{{ article.crafting }}</span></p>
            {% endif %}
            {% if article.dangerousness %}
                <p><span class="label">Nebezpečnost:</span> <span class="value">{{ article.dangerousness }}</span></p>
            {% endif %}
            {% if article.strength %}
                <p><span class="label">Síla:</span> <span class="value">{{ article.strength }}</span></p>
            {% endif %}
            {% if article.color_taste_smell %}
                <p><span class="label">Barva/chuť/zápach:</span> <span class="value">{{ article.color_taste_smell }}</span></p>
            {% endif %}
            {% if article.daily_magenergy %}
                <p><span class="label">Magy/den:</span> <span class="value">{{ article.daily_magenergy }}</span></p>
            {% endif %}
            {% if article.effect_outreach %}
                <p><span class="label">Dosah účinku:</span> <span class="value">{{ article.effect_outreach }}</span></p>
            {% endif %}
            {% if article.crafter_level %}
                <p><span class="label">Úroveň výrobce:</span> <span class="value">{{ article.crafter_level }}</span></p>
            {% endif %}
            {% if article.plane %}
                <p><span class="label">Sféra:</span> <span class="value">{{ article.plane }}</span></p>
            {% endif %}


            <p><span class="label">Popis:</span> <div class="value">{{ article.description|render_html_insecurely|safe }}</div></p>

            <p><span class="label">Přidáno:</span> <span class="value"><time datetime="{{ article.published | date:"c"  }}">{{ article.published | articleTime }}</time></span></p>
            <p><span class="label">Přečteno:</span> <span class="value">{{ article.read }}</span></p>
            <p><span class="label">Hlasovalo:</span> <span class="value">{{ article.rater_no }}</span></p>

            <p><span class="label">Autor:</span> <span class="value"><a href="#" class="author" rel="author">{{ article.author_nick }}</a></span></p>


        </header>

        <div class="content">
            {{ article.text|render_html|safe }}
        </div>
        <footer>

        </footer>

        {% if user.is_authenticated %}
            {% creation_votes creative_page_slug article.pk  %}
        {% endif %}
        {% creation_comments creative_page_slug article.pk %}

    </article>

</div>
{% endblock %}

ddcz/templates/creative-pages/commonarticle-detail.html
{% extends 'public.html' %}
{% load html %}
{% load creations %}
{% load comments %}

{% block meta_description %}{{ article.anotace }}{% endblock %}

{% block content %}
<div id="page-article-detail">
    <h1 class="page-heading">{{ heading }}</h1>
    <article>
        <header>
            <h2>{{ article.name }}{% creation_rating article.rating skin %}</h2>
            <!-- TODO
            <p>Příprava pro tisk</p>
            -->
            <table>
                <tr>
                    <th>Autor:</th>
                    <td>{% author_display article %}</td>
                </tr>
                <tr>
                    <th>Přidáno:</th>
                    <td><time datetime="{{ article.published | date:"c"  }}">{{ article.published | articleTime }}</time></td>
                </tr>
                <tr>
                    <th>Hlasovalo:</th>
                    <td>{{ article.rater_no }}</td>
                </tr>
            </table>
            <p class="synopsis">{{ article.anotace }}</p>
        </header>

        <section class="content">
            {{ article.text|render_html_insecurely|safe }}
        </section>
        <footer>
        </footer>

        {% if user.is_authenticated %}
            {% creation_votes creative_page_slug article.pk  %}
        {% endif %}
        {% creation_comments creative_page_slug article.pk %}

    </article>


</div>
{% endblock %}

ddcz/templates/creative-pages/commonarticles-list.html
{% extends 'public.html' %}
{% load html %}
{% load creations %}

{% block content %}
<div id="page-common-article">
    <h1 class="page-heading">{{ heading }}</h1>
    <ul class="article-list">
    {% for a in articles %}
        <li class="creation-detail">
            <h2><a href="{% url 'ddcz:common-article-detail' creative_page_slug=creative_page_slug article_id=a.id article_slug=a.get_slug %}">{{ a.jmeno }}</a>{% creation_rating a.pochvez skin %}</h2>
            {% if a.anotace %} 
                <p class="synopsis"><i>{{ a.anotace }}</i></p>
            {% endif %}
            <div class="table-like">
                <p><span class="label">Autor:</span> <span class="value"><a href="mailto:{{ a.autmail }}" class="author" rel="author">{{ a.autor }}</a></span></p>
                <p><span class="label">Přidáno:</span> <span class="value"><time datetime={{ a.datum | date:"r"  }}>{{ a.datum | date:"j. n. Y v H:i:s" }}</time></span></p>
                <p><span class="label">Přečteno:</span> <span class="value">{{ a.precteno }}</span></p>
                <p><span class="label">Hlasovalo:</span> <span class="value">{{ a.pocet_hlasujicich }}</span></p>
                <!--
                <p><span class="label">Příspěvků k článku:</span> <span class="value">TODO</span></p>
                -->
            </div>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

ddcz/templates/creative-pages/concept.html
{% extends 'public.html' %}
{% load html %}
{% load creations %}
{% load pages %}

{% block content %}
<div id="page-common-article">
    <h1 class="page-heading">{{ concept }}</h1>
    <article>
        <div class="content">
            {{ concept.text|render_html|safe }}
        </div>
    </article>
</div>
{% endblock %}

ddcz/templates/creative-pages/downloaditem-detail.html
{% extends 'public.html' %}
{% load html %}
{% load creations %}
{% load comments %}

{% block content %}
<div id="page-article-detail">
    <h1 class="page-heading">{{ heading }}</h1>
    <article>
        <header>
            <h2><a download href="{% url 'ddcz:download-file' download_id=article.id %}">{{ article.name }}</a>{% creation_rating a.rating skin %}</h2>
            <table>
                <tr>
                    <th>Autor:</th>
                    <td>{% author_display article %}</td>
                </tr>
                <tr>
                    <th>Přidáno:</th>
                    <td><time datetime="{{ article.published | date:"c" }}">{{ article.published | articleTime }}</time></td>
                </tr>
                <tr>
                    <th>Hlasovalo:</th>
                    <td>{{ article.rater_no }}</td>
                </tr>
                <tr>
                    <th>Popis:</th>
                    <td>{{ article.description|render_html_insecurely|safe }}</td>
                </tr>
            </table>
        </header>

        {% if user.is_authenticated %}
            {% creation_votes creative_page_slug article.pk  %}
        {% endif %}
        {% creation_comments creative_page_slug article.pk %}

    </article>


</div>
{% endblock %}

ddcz/templates/creative-pages/downloaditem-list.html
{% extends 'public.html' %}
{% load html %}
{% load creations %}
{% load pages %}


{% block content %}
<div id="page-common-article">
    <h1 class="page-heading text-red">{{ heading }}</h1>
    {% if user.is_authenticated and concept %}
        <p><a href="{% url 'ddcz:creative-page-concept' creative_page_slug %}">{{ concept }}</a></p>
    {% endif %}

    {% pagination articles %}
    <ul class="article-list">
    {% for a in articles %}
        <li class="creation-detail">
            <h2><a download href="{% url 'ddcz:download-file' download_id=a.id %}">{{ a.name }}</a>{% creation_rating a.rating skin %}</h2>

            <div class="table-like">
                <p><span class="label">Stáhnuto:</span> <span class="value">{{ a.download_counter }}</span></p>
                <p><span class="label">Formát:</span> <span class="value">{{ a.format }}</span></p>
                <p><span class="label">Autor:</span> <span class="value">{% author_display a %}</span></p>

                <p><span class="label">Velikost:</span> <span class="value">{{ a.size }}&nbsp;bytů</span></p>
                <div class="description-row"><span class="label">Popis:</span> <div class="value">{{ a.description|render_html_insecurely|safe }}</div></div>
                <p><span class="label">Přidáno:</span> <span class="value"><time datetime="{{ a.published | date:"c" }}">{{ a.published | articleTime }}</time></span></p>
                <p><span class="label">Hlasovalo:</span> <span class="value">{{ a.rater_no }}</span></p>
                <!--
                <p><span class="label">Příspěvků k článku:</span> <span class="value">TODO</span></p>
                -->
            </div>
        </li>
    {% endfor %}
    </ul>
    {% pagination articles %}
</div>
{% endblock %}

ddcz/templates/creative-pages/html-check-list.html
{% extends 'public.html' %}
{% load creations %}
{% load html %}
{% block content %}
<div id="page-article-detail">
    <h1 class="page-heading">{{ heading }}</h1>
    <h2>Příspěvky s chybným HTML</h2>
    <table>
        <tr>
            <th>Příspěvek</th>
            <th>Chyba</th>
        </tr>
        {% for result in bad_creations %}
            <tr>
                <td><a href="{% url 'ddcz:creation-detail' creative_page_slug=creative_page_slug creation_id=result.creation.id creation_slug=result.creation.get_slug %}">{{ result.creation.name }}</a></td>
                <td>{{ result.message}}
            </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

ddcz/templates/creative-pages/photo-detail.html
{% include "creative-pages/gallerypicture-detail.html" %}

ddcz/templates/creative-pages/photo-list.html
{% include "creative-pages/gallerypicture-list.html" %}