ddcz/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.views.generic.base import RedirectView, TemplateView
from django.views.decorators.cache import cache_page

from .feeds import PhorumFeed, CompleteNewsFeed
from . import views
from .views import news, tavern, misc, email
from .views.legacy import legacy_router, print_legacy_router

app_name = "ddcz"

urlpatterns = [
    path("", RedirectView.as_view(url="aktuality/", permanent=False)),
    ### Legacy redirects from stare.dracidoupe.cz
    path("index.php", legacy_router, name="legacy-router"),
    re_path(
        "code/(?P<page_category>[a-zA-Z0-9_-]+)/(?P<page_category_second>[a-zA-Z0-9_-]+)_tisk.php",
        print_legacy_router,
        name="legacy-router-print",
    ),
    re_path(
        r"^ikonky/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.USER_ICON_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-icons",
    ),
    re_path(
        r"^fotogalerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-photogallery",
    ),
    re_path(
        r"^galerie/(?P<file>.+)$",
        RedirectView.as_view(url=f"{settings.PHOTOGALLERY_MEDIA_ROOT_URL}%(file)s"),
        name="redirect-gallery",
    ),
    # It's gone, Dave
    re_path(r"^(moudrasova|img|static|skiny|chat)/", RedirectView.as_view()),
    ### Common pages for bots etc.
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    path("staticfiles/robots.txt", RedirectView.as_view(url="/robots.txt")),
    path(
        "ads.txt",
        TemplateView.as_view(template_name="ads.txt", content_type="text/plain"),
    ),
    path(
        ".well-known/security.txt",
        TemplateView.as_view(template_name="security.txt", content_type="text/plain"),
    ),
    # Prefetch for Google Chrome
    # Courtesy of https://webmasters.stackexchange.com/a/139570
    path(
        ".well-known/traffic-advice",
        TemplateView.as_view(
            template_name="traffic-advice.json",
            content_type="application/trafficadvice+json",
        ),
    ),
    ### Creations and Creative Pages
    path(
        "rubriky/<creative_page_slug>/", views.creative_page_list, name="creation-list"
    ),
    path(
        "rubriky/<creative_page_slug>/koncepce/",
        views.creative_page_concept,
        name="creative-page-concept",
    ),
    path(
        "rubriky/<creative_page_slug>/kontrola-html/",
        views.creative_page_html_check,
        name="creative_page_html_check",
    ),
    # path(
    #     "rubriky/<creative_page_slug>/<int:creation_id>-<creation_slug>/",
    #     views.creation_detail,
    #     name="creation-detail",
    # ),
    re_path(
        "^rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/$",
        views.creation_detail,
        name="creation-detail",
    ),
    re_path(
        "rubriky/(?P<creative_page_slug>\w+)/(?P<creation_id>\d+)-(?P<creation_slug>[a-zA-Z0-9_-]+)/obr_pris/(?P<image_path>.+)",  # /(?P<image_path_name>\w+)",
        views.creation_detail_image,
        name="creation-detail-image",
    ),
    re_path(
        r"obr_pris/(?P<image_path>[\w\/]+\.[\w]+)",
        views.creation_detail_image_legacy,
        name="creation-legacy-detail-image",
    ),
    # Standard list and detail are under creation pages above,
    # Those are for executing redirect to download/quest location
    path("download/<int:download_id>/", views.download_file, name="download-file"),
    path(
        "dobrodruzstvi/<int:quest_id>/",
        views.quest_view_redirect,
        name="quest-view-legacy-redirect",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)-(?P<quest_slug>[a-zA-Z0-9_-]+)/$",
        views.quest_view_redirect,
        name="quest-view",
    ),
    re_path(
        "dobrodruzstvi/(?P<quest_id>\d+)(-)?(?P<quest_slug>[a-zA-Z0-9_-]+)?/(?P<leftover>.*)$",
        views.quest_view_redirect_rest,
        name="quest-view-rest",
    ),
    ### User handling
    path("uzivatele/", views.users_list, name="users-list"),
    path("uzivatel/prihlaseni/", views.login, name="login-action"),
    path("registrace/", views.sign_up, name="sign-up"),
    path("uzivatel/odhlaseni/", views.logout, name="logout-action"),
    path(
        "uzivatel/reset-hesla/",
        views.PasswordResetView.as_view(),
        name="password-reset",
    ),
    path(
        "uzivatel/reset-hesla/hotovo/",
        views.PasswordResetDoneView.as_view(),
        name="password-reset-done",
    ),
    path(
        "uzivatel/zmena-hesla/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(),
        name="password-change",
    ),
    path(
        "uzivatel/zmena-hesla/hotovo/",
        views.PasswordResetCompleteView.as_view(),
        name="password-change-done",
    ),
    path(
        "uzivatel/<int:user_profile_id>-<nick_slug>/",
        views.user_profile,
        name="user-detail",
    ),
    path("autor/<int:author_id>-<slug>/", views.author_detail, name="author-detail"),
    ### User settings
    path("nastaveni/zmena-skinu/", views.change_skin, name="change-skin"),
    path("nastaveni/", views.user_settings, name="user-settings"),
    ### Emails
    path(
        "e-mail/antispam/potvrzeni/",
        TemplateView.as_view(template_name="emails/unsub-confirm.html"),
        name="email-antispam-confirm",
    ),
    path(
        "e-mail/antispam/<email_base64>-<unsub_token>/",
        email.antispam,
        name="email-antispam",
    ),
    ### Info sites
    path("aktuality/", news.list, name="news"),
    path("novinky/", news.newsfeed, name="newsfeed"),
    path("seznamka/", views.dating, name="dating"),
    path("seznamka/pridat/", views.misc.dating_create, name="dating-create"),
    path("inzerce/", views.market, name="market"),
    path("inzerce/pridej/", views.market_create, name="market-create"),
    path("inzerce/smaz/<int:id>/", views.market_delete, name="market-delete"),
    path("linky/", views.links, name="links-list"),
    ### Discussions & Tavern
    path("forum/", views.phorum, name="phorum-list"),
    ### RSS cheat: pretend we have unique links for items. We may in the future.
    path(
        "forum/<int:comment_id>/",
        RedirectView.as_view(url="/forum/", permanent=False),
        name="phorum-item",
    ),
    path("putyka/", tavern.list_tables, name="tavern-list"),
    path(
        "putyka/stul/<int:tavern_table_id>/prispevky/",
        tavern.table_posts,
        name="tavern-posts",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/nastenka/",
        tavern.notice_board,
        name="tavern-notice-board",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/administrace/",
        tavern.table_administration,
        name="tavern-table-admin",
    ),
    path(
        "putyka/stul/<int:tavern_table_id>/oblibit/",
        tavern.table_bookmark,
        name="tavern-bookmark",
    ),
    ### RSS & Feeds
    path(
        "rss/forum/",
        cache_page(settings.RSS_CACHE_INTERVAL)(PhorumFeed()),
        name="feed-phorum",
    ),
    path("rss/forum.xml", RedirectView.as_view(url="/rss/forum/", permanent=True)),
    path(
        "rss/novinky/",
        cache_page(settings.RSS_CACHE_INTERVAL)(CompleteNewsFeed()),
        name="feed-complete",
    ),
    path("rss/novinky.xml", RedirectView.as_view(url="/rss/novinky/", permanent=True)),
    ### Static Editorial Pages
    ### Would be easier to give them /static prefix, but it makes for ugly URL
    path(
        "co-je-draci-doupe/",
        views.editor_article,
        name="about-drd",
        kwargs={"slug": "co-je-draci-doupe"},
    ),
    path(
        "draci-manual/",
        views.editor_article,
        name="website-manual",
        kwargs={"slug": "draci-manual"},
    ),
    path(
        "otazky-a-odpovedi/",
        views.editor_article,
        name="faq",
        kwargs={"slug": "otazky-a-odpovedi"},
    ),
    path(
        "tvurci-a-redakce/",
        misc.web_authors_and_editors,
        name="web-authors-and-editors",
    ),
    path("posta/", views.postal_service, name="postal-service"),
]

dragon/urls.py
from django.urls import path

from . import views

app_name = "dragon"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("aktuality/", views.news, name="news"),
    path("level-system/", views.levelsystem, name="levelsystem"),
    path("email-test/", views.emailtest, name="emailtest"),
    path("uzivatele/", views.users, name="users"),
    path("uzivatele/<int:user_id>/zablokovat/", views.user_ban, name="user-ban"),
    path("uzivatele/<int:user_id>/odblokovat/", views.user_unban, name="user-unban"),
]

graveyard/urls.py
from graveyard.settings.base import INSTALLED_APPS
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("ddcz.urls", namespace="ddcz")),
    path("admin/", admin.site.urls),
    path("sprava/", include("dragon.urls", namespace="dragon")),
]

if settings.DEBUG and "debug_toolbar" in INSTALLED_APPS:
    import debug_toolbar

    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

ddcz/forms/commentForms.py
from django import forms
from django.http import HttpResponse
from ..models.used.discussion import Phorum


class PhorumCommentForm(forms.Form):
    text = forms.CharField(
        label="", widget=forms.Textarea(attrs={"class": "comment__textarea"})
    )
    username = forms.HiddenInput()

ddcz/views/comments.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from ..forms.comments import PhorumCommentForm, DeletePhorumCommentForm
from ..text import escape_user_input
from ..models import Phorum, ADD_PHORUM_COMMENT, DELETE_PHORUM_COMMENT


@require_http_methods(["HEAD", "GET", "POST"])
def phorum(request):
    if request.method == "POST" and request.POST["post_type"] and request.user:
        if (
            request.POST["post_type"] == DELETE_PHORUM_COMMENT
            and request.POST["submit"] == "Smazat"
        ):
            try:
                Phorum.objects.get(
                    id=request.POST["post_id"],
                    nickname=request.user.profile.nick,
                ).delete()
            except Phorum.DoesNotExist:
                messages.error(request, "Zprávu se nepodařilo smazat.")
                return HttpResponseRedirect(reverse("ddcz:phorum-list"))

        elif (
            request.POST["post_type"] == ADD_PHORUM_COMMENT
            and request.POST["submit"] == "Přidej"
        ):
            form = PhorumCommentForm(request.POST)
            if form.is_valid():
                Phorum.objects.create(
                    reputation=0,
                    registered_or_ip=1,
                    user=request.user.profile,
                    text=escape_user_input(form.cleaned_data["text"]),
                    nickname=request.user.profile.nick,
                    email=request.user.profile.email,
                )

        return HttpResponseRedirect(reverse("ddcz:phorum-list"))

    default_limit = 20
    discussions = Phorum.objects.all().order_by("-date")

    paginator = Paginator(discussions, default_limit)
    page = request.GET.get("z_s", 1)

    discussions = paginator.get_page(page)

    return render(
        request,
        "discussions/phorum-list.html",
        {
            "discussions": discussions,
            "phorum_comment_form": PhorumCommentForm(),
            "delete_form": DeletePhorumCommentForm(),
        },
    )

ddcz/views/email.py
import logging

from django.http import (
    HttpResponseRedirect,
    HttpResponseBadRequest,
)
from django.shortcuts import render
from django.urls import reverse
from django.views.decorators.http import require_http_methods

from ..email import validate_unsubscribe_token, blacklist_email
from ..models import EmailSubscriptionAuth

logger = logging.getLogger(__name__)


@require_http_methods(["HEAD", "GET", "POST"])
def antispam(request, email_base64, unsub_token):
    if not email_base64 or not unsub_token:
        return HttpResponseBadRequest("Špatný formát odhlašovacího kódu.")

    try:
        validate_unsubscribe_token(email_base64, unsub_token)
    except EmailSubscriptionAuth.DoesNotExist:
        logger.warning(
            f"User tried to unsubscribe email {email_base64}, but it wasn't found in a database"
        )
        return HttpResponseBadRequest(
            "Tento e-mail není v databázi. Nezměnil jsi ho mezitím v profilu, případně nebyl už zařazen do seznamu zakázaných e-mailů? Byla zaslána zpráva adminům, neb toto by se nemělo stát. "
        )
    else:
        if request.method == "POST":
            blacklist_email(email_base64)
            return HttpResponseRedirect(reverse("ddcz:email-antispam-confirm"))
        else:
            return render(
                request,
                "emails/antispam.html",
                {},
            )

ddcz/views/misc.py
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_http_methods

from ..models import (
    Market,
    UserProfile,
    Dating,
    Link,
    EditorArticle,
    MARKET_SECTION_CHOICES,
)
from ..forms.market import MarketForm
from ..forms.dating import DatingForm

DEFAULT_LIST_SIZE = 10


# Get an instance of a logger
logger = logging.getLogger(__name__)


@require_http_methods(["HEAD", "GET"])
def links(request):
    item_list = Link.objects.filter(is_approved="a").order_by("-published")

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "links/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def dating(request):
    item_list = Dating.objects.order_by("-published")

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "dating/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def market(request):
    item_list = Market.objects.order_by("-created")

    section = request.GET.get("sekce", None)
    if section:
        if section not in [i[0] for i in MARKET_SECTION_CHOICES]:
            raise Http404()

        item_list = item_list.filter(group=request.GET.get("sekce"))

    paginator = Paginator(item_list, DEFAULT_LIST_SIZE)
    page = request.GET.get("z_s", 1)

    items = paginator.get_page(page)

    return render(request, "market/list.html", {"items": items})


@require_http_methods(["HEAD", "GET"])
def editor_article(request, slug):
    article = get_object_or_404(EditorArticle, slug=slug)

    return render(
        request,
        "info/editor-article.html",
        {"article": article},
    )


@require_http_methods(["HEAD", "GET"])
def web_authors_and_editors(request):
    hall_of_fame = [
        {
            "user_profile": UserProfile.objects.get(nick="James Timqui"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Alcator"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Legar"),
            "role": "programátor",
        },
        {
            "user_profile": UserProfile.objects.get(nick="deshi"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Igi"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Suk"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Nathaka"),
            "role": "tribun",
        },
        {
            "user_profile": UserProfile.objects.get(nick="Kamerask"),
            "role": "tribun",
        },
    ]

    return render(
        request,
        "info/web-authors-and-editors.html",
        {
            "tribune": UserProfile.objects.get(pk=settings.TRIBUNE_ID),
            "famous_users": hall_of_fame,
        },
    )


def market_create(request):
    if request.method == "POST":
        form = MarketForm(request.POST)
        if form.is_valid():
            market_item = form.save(commit=False)
            market_item.user_profile = request.ddcz_profile
            form.save()
            return redirect("ddcz:market")
    else:
        form = MarketForm()

    return render(request, "market/create.html", {"form": form})


@login_required
@require_http_methods(["POST"])
def market_delete(request, id):
    market_item = get_object_or_404(Market, id=id)
    if market_item.user_profile == request.ddcz_profile:
        market_item.delete()
    return redirect("ddcz:market")


def dating_create(request):
    if request.method == "POST":
        form = DatingForm(request.POST)
        if form.is_valid():
            dating_item = form.save(commit=False)
            dating_item.user_profile = request.ddcz_profile
            form.save()
            return redirect("ddcz:dating")
    else:
        form = DatingForm()

    return render(request, "dating/create.html", {"form": form})


@login_required
@require_http_methods(["POST"])
def dating_delete(request, id):
    dating_item = get_object_or_404(Dating, id=id)
    if dating_item.user_profile == request.ddcz_profile:
        dating_item.delete()
    return redirect("ddcz:dating")

ddcz/templates/base/light-dark/left_menu.html
<nav id="left_menu">
    <ul class="nav_border">
        <li>
            <span class="list_heading">Rubriky</span>
            <ul>
                <li><span class="list_subheading">Tvorba</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='clanky' %}">Články&amp;Eseje</a>
                        </li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='galerie' %}">Galerie</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='fotogalerie' %}">Fotogalerie</a>
                        </li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='hrbitov' %}">Hřbitov</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Doplňky</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='dovednosti' %}">Dovednosti</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='novapovolani' %}">Nová Povolání</a>
                        </li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='noverasy' %}">Nové Rasy</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Pro PJ</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='bestiar' %}">Bestiář</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='dobrodruzstvi' %}">Dobrodružství</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='predmety' %}">Předměty</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Všeobecné</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='downloady' %}">Downloady</a></li>
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'ddcz:links-list' %}">Linky</a></li>
                        {% endif %}
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='expanze' %}">Rozvoj DrD</a></li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li>
                    <span class="list_subheading">Postavy</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='alchymistazvl' %}">Alchymista</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='alchpredmety' %}">Alchymistické předměty</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='hranicar' %}">Hraničář</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='hranicarkouzla' %}">Hraničářská kouzla</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='kouzelnikzvl' %}">Kouzelník</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='kouzla' %}">Kouzelnická kouzla</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='valecnik' %}">Válečník</a></li>
                        <li><a href="{% url 'ddcz:creation-list' creative_page_slug='zlodej' %}">Zloděj</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>


    <ul class="nav_border">
        <li>
            <span class="list_heading">Ostatní</span>
            <ul>
                <li>
                    <span class="list_subheading">Hledat</span>
                    <ul class="list_box">
                        <li><a href="https://www.google.com/?q=site:www.dracidoupe.cz">Vyhledávání</a></li>
                        <li>Rekordy a statistiky</li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Nápověda</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:about-drd' %}">Co je to Dračí Doupě?</a></li>
                        <li><a href="{% url 'ddcz:website-manual' %}">Dračí manuál</a></li>
                        <li><a href="{% url 'ddcz:faq' %}">Otázky a Odpovědi</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Kontakt</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:dating' %}" id="ddcz_nav_dating">Seznamka</a></li>
                        <li><a href="{% url 'ddcz:market' %}" id="ddcz_nav_market">Inzerce</a></li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li>
                    <span class="list_subheading">Seznamy</span>
                    <ul class="list_box">
                        <li><a href="{% url 'ddcz:web-authors-and-editors' %}">Tvůrci a Redakce</a></li>
                        <li><a href="{% url 'ddcz:users-list' %}">Uživatelé</a></li>
                    </ul>
                </li>
            </ul>
        </li>
    </ul>
</nav>

ddcz/templates/base/light-dark/right_menu.html
<nav id="right_menu">
    {% if user.is_authenticated %}
        <ul class="nav_border">
            <li><span class="list_heading">Vzhled</span>
                <ul class="list_box">
                    <li><a href="{% url 'ddcz:change-skin' %}?skin=historic&redirect={{ current_page_url }}">NeoHistoric</a>
                    </li>
                    <li><a href="{% url 'ddcz:change-skin' %}?skin=light&redirect={{ current_page_url }}">Light</a></li>
                    <li><a href="{% url 'ddcz:change-skin' %}?skin=dark&redirect={{ current_page_url }}">Dark</a></li>
                </ul>
            </li>
        </ul>
    {% endif %}
    <ul class="nav_border">
        <li><span class="list_heading">Novinky</span>
            <ul class="list_box">
                <li><a href="{% url 'ddcz:news' %}">Aktuality</a></li>
                <li><a href="{% url 'ddcz:newsfeed' %}">Novinky</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'ddcz:tavern-posts' tavern_table_id=bugfix_tavern_table_id %}">Bugfix</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
    <ul class="nav_border">
        <li><span class="list_heading">Komunikace</span>
            <ul class="list_box">
                <li><a href="{{ discord_invite_link }}">Chat (Discord)</a></li>
                <li><a href="{% url 'ddcz:phorum-list' %}" id="ddcz_nav_phorum">Fórum</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'ddcz:postal-service' %}">Pošta</a></li>
                    <li><a href="{% url 'ddcz:tavern-list' %}" id="ddcz_nav_tavern">Putyka</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
    <ul class="nav_border">
        <li><span class="list_heading">Control</span>
            <div class="list_box" id="ddcz_control">
                {% if user.is_authenticated %}
                <div class="nick" id="ddcz_nick">{{ user.username }}</div>
                <div class="state">online</div>
                {% if ddcz_profile.icon_url %}
                <p class="user_icon"><img src="{{ ddcz_profile.icon_url }}" alt="Ikonka uživatele"></p>
                {% endif %}
                <p class="stats">
                    Hlasů: {{ ddcz_profile.reputation_available }} <br>
                    Reputace: {{ ddcz_profile.reputation }}
                </p>
                <p class="admin_link">
                    <a href="{{ ddcz_profile.profile_url }}">Statistiky</a>
                    <a href="{% url 'ddcz:user-settings' %}">Nastavení</a>
                    {% if user.is_staff %}
                        <a href="{% url 'dragon:dashboard' %}">Správa</a>
                    {% endif %}
                </p>
                <form method="post" action="{% url 'ddcz:logout-action' %}">
                    {% csrf_token %}
                    <input type="submit" value="Odhlaš" id="logout_submit">
                </form>
                {% else %}
                <p><a href="{% url 'ddcz:sign-up' %}">Registrace</a></p>
                <form method="post" action="{% url 'ddcz:login-action' %}">
                    {% csrf_token %}
                    {{ login_form }}
                    <input type="submit" value="Přihlásit" id="login_submit">
                </form>
                <p><a href="{% url 'ddcz:password-reset' %}">Zapomněl jsem heslo</a></p>
                {% endif %}
            </div>
        </li>
    </ul>
    <ul class="nav_border">
        <li><span class="list_heading">Doupě jinde</span>
            <ul class="list_box">
                <li><a href="https://www.facebook.com/DraciDoupecz-47586881642/">Facebook</a></li>
            </ul>
        </li>
    </ul>
</nav>